[default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
remappings = ['@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/',
'@openzeppelin/=lib/openzeppelin-contracts/'
                 ]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
