[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
ffi = true
fs_permissions = [{ access = "read", path = "../xdapp.config.json"}]
remappings = [
    '@openzeppelin-upgradeable=lib/openzeppelin-contracts-upgradeable/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
    ]
auto_detect_remapppings = true
cache = true
cache_path = 'cache'
broadcast = 'broadcast'
gas_reports = ['*']
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
goerli = "${GOERLI_RPC_ENDPOINT}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
